### ISSUE TITLE
Marco I am still watching your github account

### ISSUE THREAD

**Issue by ying-jeanne** [marc0l92/obsidian-jira-issue#1]
Please add a fancy readme Marco, I am looking forward to seeing your new JIRA tools.

**Comment by marc0l92** [comment]
Documentation added. Now I need to understand how to use github actions.

**Comment by ying-jeanne** [comment]
what you would like to add as github actions? external PR is welcomed?

**Comment by marc0l92** [comment]
when I push a new tag I would like to create a new release with the files main.js, style.css and manifest.json.
but the file main.js is generated running npm run build.

I copied something from the web and now I need to understand what I did...
