### ISSUE TITLE
plugin error message when startup obsidian

### ISSUE THREAD

**Issue by Rick1125** [marc0l92/obsidian-jira-issue#14]
Every time start obsidian, I found following message in console log:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'push')

it seems caused by this line of code, could you please check it out?

jiraClient.ts
124        this._settings.jqlAutocomplete.functions[functionType].push(functionData.value)

**Comment by marc0l92** [comment]
Hello, thanks for reporting this issue.
Can you try to update the plugin and let me know if you still see this issue?

**Comment by Rick1125** [comment]
error message is gone, 👍 
Thanks
