### ISSUE TITLE
Any Chance for Jira Cloud Integration?

### ISSUE THREAD

**Issue by ccclapp** [marc0l92/obsidian-jira-issue#16]
Hi
Is there any chance you will update this for Jira cloud?  I expect many would like to use it.
Thanks

**Comment by marc0l92** [comment]
My company uses a private instance of Jira. But I assumed that the api would be the same with Jira Cloud.
What is the error you get?
Do you know any open project that I can access on Jira Cloud in order to test the api?

**Comment by simonPaulBergzeit** [comment]
I got it to work with my companys jira cloud instance.

First you have to create an API-Token as described here:
https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/

Then in the plugin settings in Obsidian you select Basic Auth as authentication type
with your user@company as username and the generated token as password.

**Comment by marc0l92** [comment]
Thanks @simonPaulBergzeit, I will add those information in the readme.md

**Comment by marc0l92** [comment]
Documentation in the settings panel and in the readme.md file updated

**Comment by ccclapp** [comment]
HI

Thanks, based on the ticket replies on GitHub it sounds like this will work. I am now moving away from Obsidian in favor of Jira and Evernote, but greatly appreciate your efforts

If you are interested, you may want to make this tool known to the jira userbase/marketplace.

In any event, THANKS!

Caleb C. Clapp
President
Cushing Housing Corp
617-721-9111
***@***.******@***.***>
