### ISSUE TITLE
ERR_SSL_CLIENT_AUTH_CERT_NEEDED on request

### ISSUE THREAD

**Issue by lbarbaglia** [marc0l92/obsidian-jira-issue#22]
Hello,

I configured the plugin with my private instance URL, the username and password to access it.

But when I try to add an issue, this happens: 
![image](https://user-images.githubusercontent.com/35603025/183394728-1bc79dc2-7956-4846-8ebc-5c83d8c7c446.png)

**Comment by marc0l92** [comment]
Hello,
I see there are many reason for that error:

https://techpages.net/err_bad_ssl_client_auth_cert-error/
https://www.minitool.com/news/err-bad-ssl-client-auth-cert.html

Do you use a self signed certificate for your private instance? Is the certification authority installed in your pc?

**Comment by lbarbaglia** [comment]
Thank you for your quick answer!
I just checked, the certificate is not self-signed.
![image](https://user-images.githubusercontent.com/35603025/183678590-8e0495e8-487c-44c3-8a18-533d89e8dfc3.png)
I can access the private instance correctly on Firefox (main) and also Chrome.
The computer time is already synced, I don't have any Windows updates pending.

**Comment by denniswalker** [comment]
Same issue here, but it is because the company CA certs aren't installed on the machine. Just a thought, but could we make it a configurable option to check SSL certs? https://stackoverflow.com/questions/44658269/electron-how-to-allow-insecure-https

**Comment by lbarbaglia** [comment]
I don't know if my company changed some settings on the Jira instance or if the update of the plugin fixed it but I am now able to correctly display the information of the issues in Obsidian. Thanks!

**Comment by WoodardDigital** [comment]
> Same issue here, but it is because the company CA certs aren't installed on the machine. Just a thought, but could we make it a configurable option to check SSL certs? https://stackoverflow.com/questions/44658269/electron-how-to-allow-insecure-https

@denniswalker  Did you ever figure this out? I have my own Certs at my org and haven't had the time to modify the plugin myself to  allow this.  (edit,  MTLs auth + a Custom internal CA,  all are local on my machine though)
