### ISSUE TITLE
Icon for sub-tasks not showing up 

### ISSUE THREAD

**Issue by Cratesmith** [marc0l92/obsidian-jira-issue#27]
Hi there!
I've started using this and it seems really great so far! 

I've just run into a problem where the sub-task icon shows up as missing. 
![image](https://user-images.githubusercontent.com/4616107/185495408-7ea1e69a-aa28-43c4-acda-ebb221c017e8.png)

My guess is that the asset this icon uses has changed path?

Edit: I had a little look and found that the story icon has a normal url (https://5livesstudios.atlassian.net/images/icons/issuetypes/story.png) but the subtasks are getting this icon url (https://5livesstudios.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10501?size=medium)

An interesting sidenote is that a sub task icon does exist in the same path as the working story icon. My guess is that the jira api is returning a url that obsidian is having trouble parsing?

**Comment by marc0l92** [comment]
Hello, thanks for reporting this issue.

This plugin takes the image url from the response of the retrieve issue api:
![image](https://user-images.githubusercontent.com/12623073/188264046-58716a19-59d5-4986-9f53-8e3ab7e63b1b.png)

It looks like the image related to the story type is publicly available and Obsidian.md can download it. On the other hand, the image related to the subtask needs authentication credentials to be downloaded:
```json
{"errorMessages":["You do not have permission to view the avatar."],"errors":{}}
```

I will modify the plugin in order to download the icons always using the credentials in order to fix this error.

**Comment by marc0l92** [comment]
Hello @Cratesmith @kportertx,

can you update the plugin to version 1.23.0 and let me know if you are able to see those images?

**Comment by Cratesmith** [comment]
Hi there!
I've just updated and unfortunately now all the icons don't work :(

The icons html now seem to use base64 images rather than urls but I think the data of the base64 might be corrupted (I can't get base64 converters or my web browser to display the image). 

Possibly this is some form of encoding in the response from the jira server?

Task Icon
`<img class="fit-content" src="data:image/png;base64,77+9UE5HDQoaCgAAAA1JSERSAAAAIAAAACAIBgAAAHN6eu+/vQAAAB10RVh0amlyYS1zeXN0ZW0taW1hZ2UtdHlwZQBhdmF0YXLvv70CGmEAAADvv71JREFUeO+/vWNgGAVQYFV/ZCsIW++/vR/vv71PSwzvv71n77+9Oe+/ve+/vRbvv73vv71RBwx/B++/ve+/ve+/vQnvv73vv73vv73vv73vv71477+9OO+/vWfvv70dMO+/ve+/vWfvvoPvv71T77+9MTAe77+9DkDvv70YBmDvv70077+9Au+/vTsA77+9eGDvv73vv71aFg9+BzgDEwoI77+9Eg8uA8m1eO+/vTsA77+9e++/ve+/ve+/vWLvv71g77+977+9YEzvv73vv71D77+9Ae+/ve+/ve+/vVzvv73vv73vv70D0KPvv73fv39gTO+/ve+/vUPvv70BMBwz77+9LBgPWO+/vWTvv70dMHzbhHTvv73vv70d77+9AsKD77+9ASMWAADvv73vv70y77+977+977+9LO+/vQAAAABJRU5E77+9QmDvv70=" alt="Task" title="Task">`

Subtask Icon
`<img class="fit-content" src="data:image/png;base64,77+9UE5HDQoaCgAAAA1JSERSAAAAIAAAACAIBgAAAHN6eu+/vQAAAB10RVh0amlyYS1zeXN0ZW0taW1hZ2UtdHlwZQBhdmF0YXLvv70CGmEAAABhSURBVHjvv71jYBgFUGBVf2QrCFvvv70f77+9T0sM77+9Z++/vTnvv73vv70W77+977+9UQcMHQcQC++/ve+/vQPIlR9177+977+9dQDvv73vv71z77+9Oe+/vVQL77+977+9A2jvv704Rx0wfBxA77+9bDhoHTDvv70kG34O77+9W8ek77+977+9FhAefA4Y77+9AADvv73vv71IHe+/ve+/vT4lAAAAAElFTkTvv71CYO+/vQ==" alt="Sub-task" title="Sub-task">`

**Comment by marc0l92** [comment]
Hello @Cratesmith ,
please update the plugin to version 1.27.0 and let me know if the issue is fixed.

I modified the logs related to "Image mimeType not found" in order to display the signature of the images loaded.

Can you send me some examples of this error?

**Comment by Cratesmith** [comment]
Ok I've attached the log. 
[obsidian.md-1662368220539.txt](https://github.com/marc0l92/obsidian-jira-issue/files/9488316/obsidian.md-1662368220539.txt)

Also this is really weird but I updated to the new version and... I'm still getting errors in the log but the icons are working? 

![image](https://user-images.githubusercontent.com/4616107/188410110-78a33282-a7a3-4eca-ae7a-478109f02d1d.png)

**Comment by marc0l92** [comment]
Please update the plugin to version 1.28.0 and let me know if all the errors are gone.

You see those error because I'm also downloading images that are not displayed. I will improve the code in the following releases in order to download only the images that you actually use.

**Comment by Cratesmith** [comment]
Yep! After updating there's no more errors in the log and the icons are still working

**Comment by marc0l92** [comment]
Thanks for your help

**Comment by Cratesmith** [comment]
No worries, cheers for all the work into this. It really helps a lot!
