### ISSUE TITLE
JiraCloud Auth not working anymore

### ISSUE THREAD

**Issue by qu4cks4lb3r** [marc0l92/obsidian-jira-issue#31]
After upgrading to 1.29, I can't access my Jira Cloud instance anymore. Even with the stored credentials that were working before 1.29. 

I created a new token but the problem still persists. 

Test connection always returns HTTP 401.

**Comment by jcoatelen-ledger** [comment]
+1

**Comment by nabigraphics** [comment]
same for me 😢

**Comment by nabigraphics** [comment]
I'm fixing this issue 🏃

**Comment by marc0l92** [comment]
@nabigraphics thanks for the fix
I published a new version of the plugin v1.30.0 with your fix.
