### ISSUE TITLE
v1.29.0 can't fetch any data

### ISSUE THREAD

**Issue by QuAzI** [marc0l92/obsidian-jira-issue#34]
Doesn't matter Basic Auth or Cloud Token used tests passed
![image](https://user-images.githubusercontent.com/1897605/192618782-0c8e7902-384b-4cf2-a8bb-f7ea9335cd3f.png)

But everything failed
![image](https://user-images.githubusercontent.com/1897605/192619090-5f6020fa-0506-43ea-ad69-9151efb85ec6.png)

Logs
![image](https://user-images.githubusercontent.com/1897605/192621379-34e4f2c1-45a5-4bd7-a766-89fb405010d6.png)

But if I open this link in browser everything is fine

**Comment by marc0l92** [comment]
Duplicate of #31 
Fixed in 1.30.0

**Comment by QuAzI** [comment]
Now even tests for both auth schemes failed

**Comment by QuAzI** [comment]
Bearer token passed. But Basic Auth not

**Comment by marc0l92** [comment]
are you able to give me more information?

**Comment by QuAzI** [comment]
JetBrains integration works out of the box and saved
```xml
<option name="apiType" value="REST_2_0" />
<option name="jiraVersion" value="8.14.1" />
```
REST_2_0 is the reason why I set `"apiBasePath": "/rest/api/2"` instead of `"apiBasePath": "/rest/api/latest"` in `.obsidian\plugins\obsidian-jira-issue\data.json`

not sure which additional data I can find to give

**Comment by QuAzI** [comment]
Looks like now my account requires captcha in case of Basic Auth.
All ok
