### ISSUE TITLE
Queries and searches done per account

### ISSUE THREAD

**Issue by wpvking** [marc0l92/obsidian-jira-issue#36]
Hi, I have 2 JIRA hosts, 1 private and 1 for work. They are completely unrelated. 

I want to create a note that shows me all issues from BOTH hosts that I have to work on. In the searches and queries it seems you are using the Priority field, and whenever it gets records from the priority 1 account, it does not pull issues for the priority 2 account.

Maybe in the query / search block enable a key function, where we can specify from which account to get the results from, e.g.

```jira-search
account: account1
resolution = Unresolved AND assignee = currentUser() AND status = 'In Progress' order by priority DESC
```

```jira-search
account: account2
resolution = Unresolved AND assignee = currentUser() AND status = 'In Progress' order by priority DESC
```

This way one can easily view lists for multiple accounts.

If the account key is not added, then use the default / priority #1 / only account set up.

Thanks for the plug in

**Comment by marc0l92** [comment]
Hello,
you can now specify the account to use for the jira-search fence using the keyword you suggested.

This feature is available starting from v1.39.0 of the plugin
