### ISSUE TITLE
Inline issues rendering issue

### ISSUE THREAD

**Issue by pierrefevrier** [marc0l92/obsidian-jira-issue#37]
Hi,

Thanks for this plugin, I have a problem with the vertical alignment of the inline issues.

Rendering without inline issue
![image](https://user-images.githubusercontent.com/239586/194245915-6d229903-65cf-46e9-b161-8ed309fd8dd7.png)

Rendering with inline issue
![image](https://user-images.githubusercontent.com/239586/194246035-074b5dbd-00b5-4ebd-8a3f-80ce089c2047.png)

OS : Windows
Obsidian version : v0.16.4

**Comment by marc0l92** [comment]
Thanks for reporting this issue. I will check.

**Comment by willow512** [comment]
+1 Glad I checked existing issues ;) 

![image](https://user-images.githubusercontent.com/7833251/199199974-5669641c-2e9e-4fe9-8b9e-938f2a3efebc.png)

I just discovered your plugin and I fell in love, changing my whole workflow. But this vertical alignment thingy has been bugging my obsessive compulsive mind.

**Comment by marc0l92** [comment]
The fix for this issue is available starting from version 1.33.0

Sorry if it took a lot of time...

**Comment by pierrefevrier** [comment]
Thanks for the fix.

**Comment by willow512** [comment]
It looks so much better, thank you 👍
