### ISSUE TITLE
Support for PROXY for outgoing request against JIRA

### ISSUE THREAD

**Issue by BrommD** [marc0l92/obsidian-jira-issue#38]
Hi all,

Is there a possibility to route outgoing plugin access over a HTTP proxy?
thx

Regards, Dejan

**Comment by BrommD** [comment]
nevermind, solved it other way. Can be closed, thx

**Comment by marc0l92** [comment]
Can you share how you solved the issue?

**Comment by BrommD** [comment]
Hi,

sadly using a solution, which works outside the plugin. Simply "punched" a whole into the firewall and directly accessing the Jira..

sry

Regards, Dejan

**Comment by marc0l92** [comment]
From the plugin I cannot control the proxy settings because it is not an api tha obsidian exposes.

I suppose Obsidian is using the same proxy setting of Chrome since it is based on that
