### ISSUE TITLE
Enhancement: Way to refresh table without rerendering.

### ISSUE THREAD

**Issue by pk1m** [marc0l92/obsidian-jira-issue#39]
Hey, I was wondering if adding a configuration refresh time to the jira-search would be valuable.  I use search mostly for my dashboard, but even when the cache expires my table doesn't update unless it gets re-rerendered.

**Comment by marc0l92** [comment]
Thanks for the feedbacks.
You can find this feature starting from version 1.34.0 of the plugin

**Comment by pk1m** [comment]
thank you for this.  sorry for late reply i didn't know this was worked on.  i use the list view so did not notice the change.  adding it to the list view with an option to refresh or refresh by polling might be another improvement.  thanks again!
