### ISSUE TITLE
Feature Request: Add ability to select columns to display

### ISSUE THREAD

**Issue by ddeighton** [marc0l92/obsidian-jira-issue#4]
I would like to customize the displayed columns when performing a jira-search. Is it possible to add this feature?

**Comment by derrickwheals** [comment]
This plugin is great - just what I need! Thank you for developing it. Plus 1 for the column configuration

**Comment by marc0l92** [comment]
I added the option to customize the columns you want to display in the table view.
At the moment the list of columns is quite small. Do you need additional columns?

**Comment by ddeighton** [comment]
Thanks for implementing this feature! Ideally, I'd like to choose any available field, especially custom fields. However, right now it would be very helpful to see the Due Date, Resolution, originalEstimate, and remainingEstimate.

**Comment by derrickwheals** [comment]
Thanks for implementing this! An enhancement to this would be to be able to list the required columns in the code snippet above the JQL, thus enabling query specific columns. Not sure whether this is possible though.

**Comment by marc0l92** [comment]
> Thanks for implementing this feature! Ideally, I'd like to choose any available field, especially custom fields. However, right now it would be very helpful to see the Due Date, Resolution, originalEstimate, and remainingEstimate.

Hello @ddeighton could you give me your feedback on all the standard columns I implemented.
The last step to close this issue would be to implement the customFields

**Comment by marc0l92** [comment]
In the release 1.14.0 you have a first implementation of custom fields support.
at the moment you need to specify the custom field ID that I guess is not so user friendly. so my next step is to also support the custom field name

**Comment by derrickwheals** [comment]
Hi Marco

One of the key standard fields that’s missing for me is the “Epic link”, ideally being brought back as the summary field of the issues parent epic.

Thanks
Derrick

**Comment by marc0l92** [comment]
Also in my company we use the field "Epic link", but it is actually a "custom field".
if you manage to find the ID of this field in your company jira configuration you can use it with the last release.

Otherwise you need to wait a bit more to let me implement the custom field by name instead of by ID.

**Comment by marc0l92** [comment]
Please update the plugin to the version 1.15.0 and let me know if you are able to use all the custom fields that you need.

@derrickwheals , @ddeighton

**Comment by derrickwheals** [comment]
Thanks Marco - I’ll give that a try

**Comment by derrickwheals** [comment]
Really useful with the custom fields and being able to select them in the columns section.

Thanks so much for this great plug-in!

**Comment by ddeighton** [comment]
Sorry for the delay in responding. This is amazing! Better than I expected. Thank you for implementing the columns feature. Exactly what I needed.
