### ISSUE TITLE
Jira-search to show Pull Requests information

### ISSUE THREAD

**Issue by willow512** [marc0l92/obsidian-jira-issue#43]
Hey, I love this plugin.

For my workflow I am often monitoring releases and the pull requests on them as those together are a big insight on how far along we are to a release. Your plugin already allows me to see so much from the comfort of my daily notes.

 I was wondering: is there a way to add a column to the jira-search that allows me to see the amount of pull requests on an issue, and the amount of merged pull requests?

**Comment by marc0l92** [comment]
There is a unofficial api that exposed this information, I can add a column for that

**Comment by marc0l92** [comment]
Hello, you can now use the column DEV_STATUS to show the pull requests linked to the user stories
This feature is available starting from version 1.40.0 of the plugin
