### ISSUE TITLE
Alt Text for Count badge

### ISSUE THREAD

**Issue by zoglesby** [marc0l92/obsidian-jira-issue#44]
It would be nice if you could specify the text that currently reads "Count" in a `jira-count` badge. I have several of them to see the number of closed, open, and blocked tickets in a sprint. Currently I have each one in a subheading so that I remember what is what, but allowing that text to be renamed would make it look cleaner.

**Comment by marc0l92** [comment]
You can find this feature starting from version 1.48.0.

The structure you should use is:
````
```jira-count
query: status = 'In Progress' order by priority DESC
label: here your custom label
```
````

https://marc0l92.github.io/obsidian-jira-issue/docs/components/jira-count

**Comment by zoglesby** [comment]
I just noticed this will test in Monday and let you know.

**Comment by zoglesby** [comment]
I never left any feedback, this is working. Thanks.
