### ISSUE TITLE
Auto-install, Inline Issue Prefix always on?

### ISSUE THREAD

**Issue by t3kl3ss** [marc0l92/obsidian-jira-issue#47]
Hey folks,

I auto-installed this plugin through Obsidian initially and it was working great. I noticed a problem when I would enter one or more (didn't test for a max) alphanumeric characters with a hyphen between them, like adding the date 12-9 or a range 1-9, it would automatically try to resolve for a Jira task and 404, none of these matched the format for my company's Jira, but the ones I needed worked fine.

I've only been using Obsidian for a couple months, so it wasn't a massive problem for me, I mostly worked around it and would add a space. I finally started recording some Regex notes for myself and then discovered this was a bigger issue because every time I tried entering something like 'a-z' it would try auto converting.

I tried just disabling the Inline Issue Prefix by leaving it blank first with no luck (even with restarting Obsidian between), checked the documentation to see if I was missing something, nope. Then went through a slew of updating the plugin, uninstalling/reinstalling it (both leaving Obsidian open & closing it). The last thing I tried was uninstalling it, closing it, then following the manual install instructions.

I think there might be something with the auto-install process that gets hung up on it?

If it ends up making a difference, I'm on a 2018 Macbook Pro running 12.6.1.

**Comment by marc0l92** [comment]
Hello,
you have this issue because you left the prefix for inline issues empty.
Please put the default value `JIRA:`

I will fix the plugin in order to disable this feature when this field is empty so that is not breaking all your notes.
![image](https://user-images.githubusercontent.com/12623073/206875929-b87784b5-65ed-4d12-b33c-46fb78decc3e.png)

**Comment by marc0l92** [comment]
In the setting description I wrote that this feature would have been disabled if the prefix was empty, but this was not the case until now.

Please update the plugin to version 1.38.0
In this version you can disable the parsing of inline issues as described in the setting description

**Comment by t3kl3ss** [comment]
Yup, works great now. Thanks much!
