### ISSUE TITLE
[Feature] Follow Obsidian/System Dark Mode switching

### ISSUE THREAD

**Issue by krav** [marc0l92/obsidian-jira-issue#48]
Obisidian supports having the color scheme follow the system color scheme, available under settings: Appearance -> "Base Color scheme" -> Dark/Light/Adapt to system.

I'd love for this plugin to follow the Obsidian setting instead of having it's own "Dark Mode" setting. Alternatively introducing a third "Adapt to system" option for this plugin.

**Comment by marc0l92** [comment]
Hello, you can find this feature starting from version 1.41.0 of this plugin.
Please, let me know if it works as expected.

**Comment by krav** [comment]
Thank you! That was quicker than I could ever have hoped for :) Works great, both on desktop and mobile!

**Comment by marc0l92** [comment]
Thanks for the validation
