### ISSUE TITLE
[Bug] Unable to load icons for JIRA ticket

### ISSUE THREAD

**Issue by maxgohfp** [marc0l92/obsidian-jira-issue#49]
**Describe the bug**
Firstly, thanks for creating this plugin. I love it. However, I'm creating errors when loading the icon of the ticket.

<img width="234" alt="Screenshot 2022-12-28 at 3 20 40 PM" src="https://user-images.githubusercontent.com/116135993/209774301-54ed1f9e-95e0-4e70-b411-daf7646030d1.png">

I traced through developer logs. It does seem like there's a permission issue as I tried to open the link via incognito on my browser, and there's an additional layer of authentication prior to accessing the static image. Is there a workaround that I can do?

In the network logs, I'm getting status code 302, with the response "Failed to load response data: No content available because this request was redirected".

Perhaps, I can add some static icons locally? I don't really care about the icons, but it's an eye sore when viewing through my notes.

**To Reproduce**
1. Just type `JIRA:Ticket-123`

**Expected behavior**
I expect the ticket to load the correct icon properly.

**Screenshots**

**Plugin version and platform**
- Version: 1.48.0
- [ ] Obsidian Windows
- [x] Obsidian Mac
- [ ] Obsidian Linux
- [ ] Obsidian Android
- [x] Obsidian iOS

**Comment by Rosswell** [comment]
im experiencing the same issue - if its not fixable due to permissions, perhaps an alternative would be to allow users to select the shown columns for the inline issues, as is the case with the table view?

**Comment by hilsonp** [comment]
Indeed, I get the same issue. Having a way to hide the broken icon if it is not possible to work-around the problem would be nice.

**Comment by maxgohfp** [comment]
As a workaround, I went into the compiled main.js and removed the column from the code. It looks much more appropriate now without the icons.

I can share what I change when I get sometime later if necessary.

<img width="468" alt="Screenshot 2023-02-27 at 4 43 56 PM" src="https://user-images.githubusercontent.com/116135993/221515717-01e9c134-ef51-4a3a-951d-20afcdf751ef.png">

**Comment by marc0l92** [comment]
Hello, please update the plugin to version 1.54.0. It should hide the images that I'm not able to fetch.
Since I cannot test it, let me know how it looks like
