### ISSUE TITLE
Feature Request: Link to Note

### ISSUE THREAD

**Issue by agarrharr** [marc0l92/obsidian-jira-issue#5]
I like that it links to Jira, but I would also like to be able to link to a note in my Obsidian vault. Would it be possible to add this option? It might make sense to add this after allowing custom columns and this could be one of the columns. Of course, you would need options for which folder to store the file and what format to name the file.

**Comment by marc0l92** [comment]
Sorry, I'm not sure to understand what you want me to create.
Can you write me an example?

**Comment by agarrharr** [comment]
Here's my use case. I have a folder in Obsidian called Tickets with notes about Jira tickets that I'm working on.

```
Tickets
  1 In Progress
    JIRA-567
    JIRA-561
  2 Code Review
    JIRA-456
    JIRA-457
  3 Ready for QA
  4 Done
    JIRA-357
    JIRA-455
  Tickets
```

On a note called tickets, I have this:

```
````jira-search
project=JIRA AND status!=Done AND status!=Backlog
AND assignee=123someid3333
ORDER BY priority 
````

## Incomplete

````dataview
TABLE WITHOUT ID file.link AS Key, url AS URL, title as Title, file.folder AS Status
FROM "Tickets" AND !"Tickets/4 Done"
WHERE file.name !="Tickets"
SORT status
````
```

I use the obsidian-lira-issue plugin at the top to see all active tickets assigned to me. But unfortunately, using that plugin, there is no way to link to my notes, so I use the dataview plugin down below to show a table of my ticket notes. The first column, Key, is a link to the note.

What I would like to do instead is have a link to my note in the jira-search results. Perhaps the syntax could look something like this:

```
````jira-search
TABLE ticket.url AS Key, ticket.summary AS Summary, ticket.note_link AS Note, ticket.status AS Status
project=JIRA AND status!=Done AND status!=Backlog
AND assignee=123someid3333
ORDER BY priority 
````
```

Another benefit of this would be that you could choose which columns you want to show.

**Comment by agarrharr** [comment]
You could also get rid of the option in the plugin to render a Table or List and this could be the syntax for a list.

````
```jira-search
LIST
project=JIRA AND status!=Done AND status!=Backlog
AND assignee=123someid3333
ORDER BY priority 
```
````

**Comment by marc0l92** [comment]
this feature is now available starting from version 1.10.0.
you can create a fence like this:

	```jira-search
	type: TABLE
	query: project=JIRA AND status!=Done AND status!=Backlog AND assignee=123someid3333 ORDER BY priority 
	columns: Key, Summary, Notes, Status
	```

Please test it and let me know your feedbacks

**Comment by agarrharr** [comment]
Yay! Thank you so much!

**Comment by marc0l92** [comment]
With the last update you can add in the jira-search table the frontmatter fields of your notes linked to the issues
