### ISSUE TITLE
[Bug] Issues not loading properly in dataview block

### ISSUE THREAD

**Issue by kimdre** [marc0l92/obsidian-jira-issue#56]
**Describe the bug**
When I try to show a list of my open tasks with dataview, which also contain jira issues, the dataview block seems to be stuck on "Loading".

However, when I remove the Jira Issue from my tasks list, dataview suddenly reloads the block with also showing the jira issue in the list before reloading the block right after.

**To Reproduce**
1. Create dataview list of tasks which contain jira issues
2. Check dataview list
3. Remove jira issues from tasks
4. Check dataview list again

**Expected behavior**
Dataview Block should load and show the jira issues

**Screenshots**

1. Dataview block (Offene Aufgaben) is stuck on "Loading" after adding the jira issue to my tasks (Neue Aufgaben) below:
![image](https://user-images.githubusercontent.com/27567533/212033132-b4bbc90b-c4df-4f43-a0f1-72a7786795af.png)

1. After removing the Jira Issue from the list below the issue appears in the dataview block above for a brief moment (about 1-2 seconds until dataview block reloads)
![image](https://user-images.githubusercontent.com/27567533/212034544-3a2d541e-75d8-46f3-be4a-da6fc5dfb1de.png)

2. After dataview reloads the issue disappears again
![image](https://user-images.githubusercontent.com/27567533/212034655-b7d9f7b4-3ec7-4e31-bade-6e20e18ec90f.png)

**Plugin version and platform**
- Jira Issue Version: 1.50.0
- Dataview Version: 0.5.53
- [x] Obsidian Mac

**Comment by kimdre** [comment]
After a bit of testing it seems the issue only occurs when I add issues with the `JIRA:`-Prefix.
When I use the url to the issue instead of using the Prefix the dataview block loads.

**Comment by marc0l92** [comment]
Sorry but I'm not able to reproduce the issue. Can you give me more details?

Here the test I did:
![screentogif](https://github.com/marc0l92/obsidian-jira-issue/assets/12623073/1fbbf677-1902-42bd-a4a7-a12d9b771955)
