### ISSUE TITLE
[Feature] Get list of user's tasks in Confluence

### ISSUE THREAD

**Issue by jeffmadison** [marc0l92/obsidian-jira-issue#58]
**Is your feature request related to a problem? Please describe.**
My team uses Jira for development work, but they also use the Tasks functionality on Confluence pages to assign me various work (review a page, schedule a meeting, etc.). I'd like to see those within Obsidian, too.

For example, if somebody adds the following to a Confluence page, it results in me having an assigned task with a due date:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/5124361/212161018-d0bbcfbd-33d3-4bfc-b2c8-ac15936f2a65.png">

**Describe the solution you'd like**
A new syntax (or a new separate Obsidian plug-in) to retrieve Confluence Cloud tasks. I'm assuming this would use their [inline tasks API](https://developer.atlassian.com/cloud/confluence/rest/v1/api-group-inline-tasks/).

By default it would display basic information about the task including its title and due date, although the name of the containing page would be handy if possible. By default it would only show tasks that are 1/ assigned to me and 2/ incomplete, but a query syntax could allow broader results and display columns.

Although the Confluence API also has a `PUT` operation to mark a task as completed, that strikes me as dangerous and/or unnecessary since I'd normally want to open the Confluence page to see the overall context before marking a task as complete.

Ideally the Confluence tasks would also be visible to the Obsidian plugins `Tasks` and `Reminder`.

**Describe alternatives you've considered**
Other plugins that allowing embedding an iframe to Confluence's page that displays your tasks (`https://yourcompany.atlassian.net/wiki/plugins/inlinetasks/mytasks.action`) would be ugly and likely not work because of authentication.

**Comment by marc0l92** [comment]
Hello,
we use those type of task in my company as well.
I'm just not sure this feature fits in the scope of this plugin that is mainly dedicated to Jira.

I would see this feature in a separate plugin

**Comment by jeffmadison** [comment]
> I would see this feature in a separate plugin

Good idea. :-)
