### ISSUE TITLE
[Feature] Add changelog support for the "Plugin Update Tracker" plugin

### ISSUE THREAD

**Issue by Bloodsucker** [marc0l92/obsidian-jira-issue#59]
**Is your feature request related to a problem? Please describe.**
When a plugin gets an update the "Plugin Update Tracker" plugin in Obsidian is useful to manage and to read the release notes from the editor. However, this plugin doesn't support that. Can we have it?

**Describe the solution you'd like**
Have support for the Plugin Update Tracker, which I'm assuming is by adding the release notes somewhere.

**Describe alternatives you've considered**
--

**Additional context**
Plugin Update Tracker - https://github.com/swar8080/obsidian-plugin-update-tracker

**Comment by marc0l92** [comment]
Hello, I configured the release workflow in order to generate the release notes that "Plugin Update Tracker" should be able to parse.

I was not aware of this plugin, it is really useful.

Let me know if you are able to see the release notes.

**Comment by Bloodsucker** [comment]
![Screenshot_20230117-195411](https://user-images.githubusercontent.com/842676/212986700-9d4887d1-9695-41c0-a47f-3f727b8a404e.png)

It does work! Awesome. Thank you very much for maintenance of the plugin.
