### ISSUE TITLE
[Feature] Add issue status to html title attribute

### ISSUE THREAD

**Issue by FabianoLothor** [marc0l92/obsidian-jira-issue#67]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/2192995/215254347-55d003d9-bb93-467b-9eed-1c6bc8542050.png)

Currently the issue status doesn't have a html title what makes impossible to do any css query selector to customize the statuses colors.

**Describe the solution you'd like**

Add a valid html title to the issue status element.

**Describe alternatives you've considered**

js-snippet, using `:contains`, via CSS is currently impossible

**Additional context**

- [x] Check the existing feature request and vote with a 👍 the one you like

**Comment by marc0l92** [comment]
Hello,
I wanted to use the title to show the status description so that you can see it while hovering on the status with your mouse.

If you want to customize the color I can add a dedicated html attribute with the status content

**Comment by FabianoLothor** [comment]
It would be nice @marc0l92.

`data-status` or something like that, because as I mentioned, the only way to customize the status colors is using JS.

Using only CSS is currently impossible.

Thank you for the heads up!

**Comment by marc0l92** [comment]
You should be able to see this tag starting from version 1.52.0 of this plugin
