### ISSUE TITLE
Integrating with Microsoft SSO

### ISSUE THREAD

**Issue by deanpribetic** [marc0l92/obsidian-jira-issue#7]
Hey Marco! I just installed this plugin and it looks very promising. However, I login to Jira via authentication through the Microsoft SSO platform. This means the response from Jira is the HTML directing me to sign in before I can get access. Any thoughts on how I might work around this?

**Comment by marc0l92** [comment]
I don't really know how Microsoft SSO works.
But I suppose that at some point is using a token to access the Jira API.

Maybe I can give you an example of API that this plugin is calling and you can tell me how the response looks like.
I need some example to guess how this protocol works so I can add the support for it.

**Comment by marc0l92** [comment]
The API the plugin uses looks like this:
```
https://jira.secondlife.com/rest/api/latest/issue/OPEN-123
<host>/rest/api/latest/issue/<issueKey>
```

**Comment by deanpribetic** [comment]
Thanks! I am looking into this. Will let you know.

**Comment by deanpribetic** [comment]
Only way to avoid the re-direct from my end is by being behind my corporate VPN. Will go forward on that basis.
