### ISSUE TITLE
[Bug] API getSprints needs an extra query param startAt for when we have more than 50 sprints

### ISSUE THREAD

**Issue by jmkhael** [marc0l92/obsidian-jira-issue#75]
**Describe the bug**
When a given board has more than 50 sprints already (which is the cap of maxResults), there is no way to go beyond that.
JIRA API accepts a query param `startAt`

**To Reproduce**
1. Call the API with a board id having more than 50 sprints, 
2. notice you cannot go past that max

**Expected behavior**
Be ble to paginate results with the help of startAt query param. 
This would get resolved into a ReST request equivalent to:
https://jira.domain.com/rest/agile/1.0/board/3236/sprint?maxResults=50&startAt=100

**Plugin version and platform**
- Version: latest
- [x] Obsidian Windows

**Comment by marc0l92** [comment]
Thanks for reporting this issue, the fix has been released in version 1.53.0
