### ISSUE TITLE
Issues are not rendered on iOS due to Buffer not being available

### ISSUE THREAD

**Issue by marcus-crane** [marc0l92/obsidian-jira-issue#9]
Hi there,

I use this plugin on my desktop but I also use Obsidian on mobile and presumably the mobile version doesn't have access to a module that is available on desktop.

From memory, Buffer is part of the Node standard library so perhaps there needs to be a polyfill for the mobile version.

I haven't done much with Obsidian plugins yet but I know enough about Node that I'm happy to try and debug this myself and file a PR 🙂

![60A3F8FD-20A3-4F77-A835-E002498A91CD](https://user-images.githubusercontent.com/14816406/166415302-d8e408a1-8751-4aae-aa94-e640bde76c2f.jpeg)

**Comment by marcus-crane** [comment]
Took me a bit to figure out how to test this stuff on mobile (I used https://github.com/TfTHacker/obsidian42-brat) but I got a fix working that I've PRed 🙂

**Comment by marcus-crane** [comment]
The plugin works really well on mobile after this fix. I reduced the table to 3 columns (that's all I care about) which is about the maximum size the non-responsive table can get before it's as wide as the screen. The issue there is just that the whole page overflow out of the viewport instead of the table being forced into a scrollable state.

**Comment by marc0l92** [comment]
I implemented the fix in version 1.11.0
Please test it and let me know your feedbacks.

I will also test a bit more the UI on mobile in order to implement an horizontal scrolling

**Comment by marcus-crane** [comment]
Just updated the plugin on mobile and yep, it continues to work just as you'd expect so marking this issue as closed. Thanks again!
