### ISSUE TITLE
[Feature] Add link in jira-search to open Jira search website

### ISSUE THREAD

**Issue by qu4cks4lb3r** [marc0l92/obsidian-jira-issue#97]
**Is your feature request related to a problem? Please describe.**
When using jira-search, it takes long to share the results of the query or play around with the JQL. 

**Describe the solution you'd like**
Allow to open the Jira search website via a link in the footer of jira-search. 

- [x] Check the existing feature request and vote with a 👍 the one you like

**Comment by marc0l92** [comment]
Thanks for the pull request. Your feature will be available in 1.55.0
